#!/usr/bin/env bash

set -exo pipefail

declare SERVICE_NAME

main() {
  SERVICE_NAME=$1

  if [[ -z $SERVICE_NAME ]]; then
    help >&2
    exit 1
  fi

  mix_new 
}

mix_new() {
  local template_folder
  template_folder="$(dirname "${BASH_SOURCE[0]}")/elixir_template/"

  if [[ -d $template_folder ]]; then
    mkdir -p "$(pwd)/${SERVICE_NAME}"
    cp -R "${template_folder}" "$(pwd)/${SERVICE_NAME}"
  fi

}

help() {
  echo "Usage:"
  echo "  ./generate-elixir-service <service-name>"
}

main "$@"
