#!/bin/bash

set -exo pipefail

main() {
  local service_name=$1

  if [[ -z $service_name ]]; then
    help
    exit 1
  fi

  mix_new $service_name
}

mix_new() {
  $(mix new $1)
}

help() {
  echo "Usage:"
  echo "  ./generate-elixir-service <service-name>"
}

main "$@"