#!/bin/bash

set -euxo pipefail

main() {
  local service_name=$1

  if [[ -z $service_name ]]; then
    help
    exit 1
  fi
}

help() {
  echo "Usage:"
  echo "  ./generate-elixir-service <service-name>"
}

main "$@"